GET http://localhost:5000/api/productos HTTP/1.1

###

GET http://localhost:5000/api/productos/64644579c4ee36d65369e1c5 HTTP/1.1

###
POST http://localhost:5000/api/productos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Gaseosa Coca-Cola",
    "categoria": "Electro Hogar",
    "precio": 650,
    "img": "https://ardiaprod.vtexassets.com/arquivos/ids/245127-1200-auto?v=638121502666400000&width=1200&height=auto&aspect=true"
}

###

PUT http://localhost:5000/api/productos/64644c25c4ee36d65369e1cd HTTP/1.1
Content-Type: application/json

{
    "nombre": "Taladro",
    "categoria": "Herramientas",
    "precio": 10000,
    "img": "https://maquinariasboedo.com/wp-content/uploads/2014/11/CARATULA-3.png"
}

###

DELETE http://localhost:5000/api/productos/646c2a6fde7e89610a0cd91e HTTP/1.1

###

GET http://localhost:5000/api/producto/64644c25c4ee36d65369e1cd HTTP/1.1

###

GET http://localhost:5000/api/usuarios HTTP/1.1




### usuarios----------------

GET http://localhost:5000/api/usuarios HTTP/1.1

###
POST http://localhost:5000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "usuario": "dota2",
    "email": "dota23@email.com",
    "password": "contraseña1234"
}

###

POST http://localhost:5000/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "dota23@email.com",
    "password": "contraseña1234"
}


###--------------------------

GET http://localhost:5000/api/carrito HTTP/1.1

###

GET http://localhost:5000/api/carrito/64644579c4ee36d65369e1c5 HTTP/1.1

###
POST http://localhost:5000/api/carrito HTTP/1.1
Content-Type: application/json

{
    "_id":25,
    "nombre": "Gaseosa Coca-Cola",
    "categoria": "Electro Hogar",
    "precio": 650,
    "cantidad":32,
    "img": "https://ardiaprod.vtexassets.com/arquivos/ids/245127-1200-auto?v=638121502666400000&width=1200&height=auto&aspect=true"
}

###

PUT http://localhost:5000/api/carrito/64644c25c4ee36d65369e1cd HTTP/1.1
Content-Type: application/json

{
    "_id": "64644c25c4ee36d65369e1cd",
    "nombre": "Taladro",
    "categoria": "Herramientas",
    "precio": 10000,
    "img": "https://maquinariasboedo.com/wp-content/uploads/2014/11/CARATULA-3.png",
    "cantidad": 4
}

###

DELETE http://localhost:5000/api/carrito/64794024ef84f5ab8a1e3cba HTTP/1.1
